#!/usr/bin/python

import time
import curses as crs
import argparse

parser = argparse.ArgumentParser(description='timer app')
parser.add_argument('time', type = str, help = 'time to count to')
args = parser.parse_args()
                    
stdscr = crs.initscr()
crs.start_color()
crs.curs_set(0)
crs.use_default_colors()
stdscr.keypad(1)
stdscr.scrollok(1)

crs.init_pair(1, crs.COLOR_WHITE, -1)
crs.init_pair(2, crs.COLOR_WHITE, crs.COLOR_BLACK)
crs.init_pair(3, crs.COLOR_BLACK, crs.COLOR_WHITE)

def get_time(inputString):
    """interpret the input as a number of seconds"""
    if inputString == "tea":
        return 180
    else:
        conversion = [1, 60, 60*60]
        return sum(int(digit)*conv for digit, conv
                   in zip(inputString.split(":")[::-1], conversion))
    
def make_time(secs):
    """format a time interval (in seconds) into a pretty string"""
    units = [str(secs/3600),
             str(secs%3600/60),
             str(secs%60)]

    for i,s in enumerate(units):
        if int(s)<10:
            units[i] = "0"+s
            
    return ":".join(units)
    

def bar(total, current, length):
    n = int(float(current)/total*length)
    return '['+(length-n)*'#'+(n)*'.'+']'


def main_timer():
    init_time = get_time(args.time)
    rem_time = init_time
    
    while rem_time:
        maxHeight, maxWidth = stdscr.getmaxyx()

        rem_time -= 1
        stdscr.addstr(maxHeight/2,
                      1,
                      make_time(init_time - rem_time) + ' ' +
                      bar(init_time, rem_time, maxWidth - 22) + ' ' +
                      make_time(init_time),
                      crs.color_pair(1))
        stdscr.refresh()
        time.sleep(1)
        stdscr.erase()

def time_up():
    color_ind = 2
    dt = 0.5
    t = 0
    while t < 10:
        maxHeight, maxWidth = stdscr.getmaxyx()

        for i in range(maxWidth):
            for j in range(maxHeight):
                stdscr.insstr(j, i, " ", crs.color_pair(color_ind))

        stdscr.addstr(maxHeight/2, maxWidth/2-4, "time up!", crs.color_pair(color_ind))
        if color_ind == 2:
            color_ind = 3
        elif color_ind == 3:
            color_ind = 2
        stdscr.refresh()
        time.sleep(dt)
        stdscr.erase()
        t += dt   
    crs.nocbreak()
    stdscr.keypad(0)
    stdscr.scrollok(0)
    crs.curs_set(1)
    crs.echo()
    crs.endwin()

        
if __name__ == '__main__':
    try:
        main_timer()
        time_up()
    except KeyboardInterrupt:
        crs.nocbreak()
        stdscr.keypad(0)
        stdscr.scrollok(0)
        crs.curs_set(1)
        crs.echo()
        crs.endwin()
